from pywinauto.application import Application
import time
mainwindow = Application(backend='uia').connect(title="Ansys Electronics Desktop 2022 R1 - Project1 - RMxprtDesign1 - Machine - [Project1 - RMxprtDesign1 - Machine]")
dig = mainwindow.window(title="Ansys Electronics Desktop 2022 R1 - Project1 - RMxprtDesign1 - Machine - [Project1 - RMxprtDesign1 - Machine]")
dig.restore()
# dig.maximize()
# time.sleep(1)
# dig.restore()
# too = dig.child_window(title="Window", control_type='MenuItem').wrapper_object()
# too.click_input()
# to = dig.child_window(title="Scripting",control_type='Button').wrapper_object()
# to.click_input()
# t = dig.child_window(title="Run Script...", control_type='MenuItem').wrapper_object()
# t.click_input()
# dig1 = dig.child_window(title="Run Script",class_name="#32770")
# m = dig1.child_window(title="文件名(N):", control_type='Edit').wrapper_object()
# m.type_keys(r'D:\BaiduNetdiskDownload\ANSYS Electronics Suite 2022 R1')
# mm = dig1.child_window(found_index=0, title="打开(O)", control_type='Button').wrapper_object()
# mm.click_input()
# too = dig.child_window(title="Analysis", control_type='TreeItem').wrapper_object()
# too.click_input(button='right')
# mai = Application(backend='uia').connect(title="上下文")
# dig1 = mainwindow.window(title="上下文")
# too = dig1.child_window(name="Add Solution Setup...", control_type='MenuItem')
# too.click_input()
too = dig.child_window(title="Tools",control_type='MenuItem').wrapper_object()
too.click_input()
too = dig.child_window(title="Options",control_type='MenuItem').wrapper_object()
too.click_input()
too = dig.child_window(title="HPC and Analysis Options...",control_type='MenuItem').wrapper_object()
too.click_input()
too1 = dig.child_window(title="Edit...",control_type='Button').wrapper_object()
too1.click_input()
too1 = dig.child_window(found_index=5,control_type="Edit").wrapper_object()
too1.click_input()