from pywinauto.application import Application
import time
import sys,logging
wei = Application(backend='uia').connect(process=6692)
dig = wei.window(class_name="WeChatMainWndForPC")
dig.maximize()
dig.restore()
# dig.print_control_identifiers()
# to = dig.child_window(title="通讯录", control_type="Button").wrapper_object()
# to.click_input()
# too = dig.child_window(title="搜索", control_type='Edit').wrapper_object()
# too.click_input()
# too.type_keys('jjz')
# time.sleep(1)
# tp = dig.child_window(title='jjz', control_type='ListItem').wrapper_object()
# tp.click_input()
# tp = dig.child_window(title='输入',control_type ='Edit').wrapper_object()
# tp.click_input()
# tp.type_keys('杀掉')
# tp = dig.child_window(title='sendBtn',control_type='Button').wrapper_object()
# tp.click_input()
to = dig.child_window(title="聊天文件",control_type='Button').wrapper_object()
to.click_input()
too = wei.window(class_name="FileListMgrWnd")
too1 = too.child_window(title="最近使用", control_type="Button").wrapper_object()
too1.click_input()
time.sleep(1)
too1 = too.child_window(title="全部", control_type="Button").wrapper_object()
too1.click_input()
too1 = too.child_window(title="搜索文件名 / 联系人 / 群聊名称", control_type='Edit').wrapper_object()
too1.click_input()
too1.type_keys("电机参数说明")
too1 = too.child_window(title='电机参数说明.xlsx', control_type='ListItem').wrapper_object()
too1.click_input()